#!/usr/bin/env bash

export OPENPI_ROOT="$(cd "$(dirname "$BASH_SOURCE")/../.." && pwd)"
test -n "$OPENPI_DATA_HOME" || OPENPI_DATA_HOME="$OPENPI_ROOT/data"
test -n "$HF_LEROBOT_HOME" || HF_LEROBOT_HOME="$OPENPI_DATA_HOME/lerobot"
test -n "$OPENPI_ASSETS_DIR" || OPENPI_ASSETS_DIR="$OPENPI_ROOT/assets"
test -n "$OPENPI_CHECKPOINT_DIR" || OPENPI_CHECKPOINT_DIR="$OPENPI_ROOT/checkpoints"
test -n "$OPENPI_JAX_CACHE_DIR" || OPENPI_JAX_CACHE_DIR="$OPENPI_ROOT/.cache/jax"
test -n "$CR3_O6_CONFIG_DIR" || CR3_O6_CONFIG_DIR="$OPENPI_ROOT/examples/cr3_o6/deploy/config"
test -n "$CR3_O6_DEPLOY_PYTHON" || CR3_O6_DEPLOY_PYTHON=python3.12
export OPENPI_DATA_HOME HF_LEROBOT_HOME OPENPI_ASSETS_DIR
export OPENPI_CHECKPOINT_DIR OPENPI_JAX_CACHE_DIR CR3_O6_CONFIG_DIR
export CR3_O6_DEPLOY_PYTHON
